### ISSUE TITLE
Update division-id submodule

### ISSUE THREAD

**Issue by patcon** [opencivicdata/python-opencivicdata-divisions#5]
As it stands, I don't think this commit is yet respected in the canadian scrapers due to this submodule pointing to an old commit:
https://github.com/opencivicdata/ocd-division-ids/commit/7fff603b60869010bce545346ad3aafdc2a94d8f

Would there be an large repercussions to our updating it?

cc: @jpmckinney

**Comment by jpmckinney** [comment]
In Canada's scrapers, I just point to a local CSV with:

```python
os.environ['OCD_DIVISION_CSV'] = os.environ.get('OCD_DIVISION_CSV', os.path.join(os.path.abspath(os.path.dirname(__file__)), 'scrapers/country-{}.csv'))
```

**Comment by patcon** [comment]
Hm. Weird. When I wasn't setting the OCD_DIVISION_CSV to use [my custom toronto csv](https://github.com/patcon/scrapers_to_app/blob/master/country-ca-toronto.csv), I was getting duped posts with the fancy emdash... not sure what's up, but you're right that it's not upstream. dah well
