### ISSUE TITLE
instead of submodule for divisions, dynamically download divisions as needed

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/python-opencivicdata-divisions#9]
I'm curious how others (cc @fgregg, @jpmckinney) feel about this.

It seems like we could:
- shrink the package install
- get away from the necessity for a separate package for these, possibly just recombining this with python-opencivicdata-django (python-opencivicdata instead? kill the necessity for a namespace package?)
- not have to do a release to include the latest ocd-division-ids 

If we had the package download the appropriate divisions file from GitHub at runtime as needed.  At worst this would be a ~20MB (US) download

**Comment by jpmckinney** [comment]
In my case I use the `OCD_DIVISION_CSV` environment variable to use whatever file I want instead of what's distributed in this package, so this is fine with me (as long as we preserve that override functionality).

**Comment by jamesturk** [comment]
ah forgot that was even there, good call.  we can make sure that works if we go forward w/ this
